In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
# ml
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


In [14]:
df = pd.read_csv('startups.csv')

In [15]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [16]:
sns.pairplot(df)

In [17]:

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [18]:
# encoding 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [19]:
df['State'].value_counts()

New York      17
California    17
Florida       16
Name: State, dtype: int64

In [20]:
st = ColumnTransformer(transformers=[('encoder',OneHotEncoder() , [3])] , remainder='passthrough')
x = np.array(st.fit_transform(x))

In [21]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [22]:
X_train , X_test , y_train , y_test = train_test_split(x,y,test_size=.20)

In [23]:
model = LinearRegression()
model.fit(X_train , y_train)

LinearRegression()

In [24]:
model.coef_

array([-5.56589258e+01,  1.33024095e+03, -1.27458203e+03,  8.03869841e-01,
       -3.37873118e-02,  3.09531718e-02])

In [25]:
model.intercept_

50225.07801959797

In [26]:
## predict

In [27]:
model.predict([[1,0,0,100000,120000,20000]])

array([127120.98916764])

In [28]:
y_pred = model.predict(X_test)
y_pred

array([150624.64417827, 116047.65574911,  47637.97169482, 172858.76307865,
       135725.59953219,  45618.68591677,  99326.82431129, 155082.78089478,
       102138.10286689, 113233.8573482 ])

In [30]:
y_test

array([132602.65, 111313.02,  35673.41, 182901.99, 144259.4 ,  64926.08,
        96778.92, 149759.96, 103282.38, 122776.86])

In [31]:

from sklearn.metrics import r2_score

r2_score(y_test , y_pred)

0.9286969719409371